USE [master]
GO
/****** Object:  Database [OfficeDB]    Script Date: 15-08-2021 11:47:52 ******/
CREATE DATABASE [OfficeDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OfficeDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\OfficeDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OfficeDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\OfficeDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [OfficeDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OfficeDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [OfficeDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [OfficeDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [OfficeDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [OfficeDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [OfficeDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [OfficeDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [OfficeDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [OfficeDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [OfficeDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [OfficeDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [OfficeDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [OfficeDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [OfficeDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [OfficeDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [OfficeDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [OfficeDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [OfficeDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [OfficeDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [OfficeDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [OfficeDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [OfficeDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [OfficeDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [OfficeDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [OfficeDB] SET  MULTI_USER 
GO
ALTER DATABASE [OfficeDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [OfficeDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [OfficeDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [OfficeDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [OfficeDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [OfficeDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [OfficeDB] SET QUERY_STORE = OFF
GO
USE [OfficeDB]
GO
/****** Object:  Table [dbo].[Employee]    Script Date: 15-08-2021 11:47:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employee](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[EmployeeName] [nvarchar](50) NULL,
	[Salary] [decimal](18, 2) NULL,
	[DOJ] [date] NULL,
 CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FileData]    Script Date: 15-08-2021 11:47:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FileData](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FileName] [nvarchar](500) NULL,
	[FileExtension] [nvarchar](50) NULL,
	[MimeType] [nvarchar](50) NULL,
	[FilePath] [nvarchar](500) NULL,
 CONSTRAINT [PK_File] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [OfficeDB] SET  READ_WRITE 
GO
